"""Generate harness-specific agent files from the canonical agent profile.

Sources (edit these):
  .agents/skills/<name>/...        shared skills (Codex reads these directly)
  agent-profile/agents/<name>.md   model-tier agents (frontmatter + instructions)

Generated (never edit by hand):
  .claude/skills/<name>/...        copy of the shared skills for Claude Code
  .claude/agents/<name>.md         Claude Code subagents
  .codex/agents/<name>.toml        Codex custom agents

Usage:
  uv run python tools/sync_agent_profile.py           # write outputs
  uv run python tools/sync_agent_profile.py --check   # exit 1 if outputs are stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_SRC = ROOT / ".agents" / "skills"
AGENTS_SRC = ROOT / "agent-profile" / "agents"
CLAUDE_SKILLS = ROOT / ".claude" / "skills"
CLAUDE_AGENTS = ROOT / ".claude" / "agents"
CODEX_AGENTS = ROOT / ".codex" / "agents"
MANAGED_DIRS = (CLAUDE_SKILLS, CLAUDE_AGENTS, CODEX_AGENTS)

NOTICE = "generated by tools/sync_agent_profile.py from agent-profile/agents/{name}.md — do not edit"
GENERATED_README = (
    "# Generated\n\nEverything in this directory is generated by `tools/sync_agent_profile.py`.\n"
    "Edit the sources (`.agents/skills/`, `agent-profile/agents/`) and re-run the script.\n"
)

REQUIRED = ("name", "description", "claude_model", "codex_model")


def parse_agent(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise SystemExit(f"{path}: missing frontmatter")
    head, body = text[4:].split("\n---\n", 1)
    meta = {}
    for line in head.splitlines():
        if line.strip():
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()
    missing = [k for k in REQUIRED if k not in meta]
    if missing:
        raise SystemExit(f"{path}: missing {', '.join(missing)}")
    if meta["name"] != path.stem:
        raise SystemExit(f"{path}: name '{meta['name']}' must match the filename")
    return meta, body.strip() + "\n"


def claude_agent(meta: dict[str, str], body: str) -> str:
    lines = ["---", f"name: {meta['name']}", f"description: {json.dumps(meta['description'], ensure_ascii=False)}",
             f"model: {meta['claude_model']}"]
    if meta.get("claude_effort"):
        lines.append(f"effort: {meta['claude_effort']}")
    if meta.get("claude_tools"):
        lines.append(f"tools: {meta['claude_tools']}")
    lines += ["---", "", f"<!-- {NOTICE.format(name=meta['name'])} -->", "", body]
    return "\n".join(lines)


def toml_multiline(text: str) -> str:
    return '"""\n' + text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"') + '"""'


def codex_agent(meta: dict[str, str], body: str) -> str:
    lines = [f"# {NOTICE.format(name=meta['name'])}",
             f"name = {json.dumps(meta['name'], ensure_ascii=False)}",
             f"description = {json.dumps(meta['description'], ensure_ascii=False)}",
             f"model = {json.dumps(meta['codex_model'], ensure_ascii=False)}"]
    if meta.get("codex_effort"):
        lines.append(f"model_reasoning_effort = {json.dumps(meta['codex_effort'], ensure_ascii=False)}")
    if meta.get("codex_sandbox"):
        lines.append(f"sandbox_mode = {json.dumps(meta['codex_sandbox'], ensure_ascii=False)}")
    lines.append(f"developer_instructions = {toml_multiline(body)}")
    return "\n".join(lines) + "\n"


def expected_outputs() -> dict[Path, bytes]:
    out: dict[Path, bytes] = {}
    for src in sorted(SKILLS_SRC.rglob("*")):
        if src.is_file():
            out[CLAUDE_SKILLS / src.relative_to(SKILLS_SRC)] = src.read_bytes()
    out[CLAUDE_SKILLS / "GENERATED.md"] = GENERATED_README.encode()
    for src in sorted(AGENTS_SRC.glob("*.md")):
        meta, body = parse_agent(src)
        out[CLAUDE_AGENTS / f"{meta['name']}.md"] = claude_agent(meta, body).encode()
        out[CODEX_AGENTS / f"{meta['name']}.toml"] = codex_agent(meta, body).encode()
    return out


def existing_files() -> set[Path]:
    return {p for d in MANAGED_DIRS if d.exists() for p in d.rglob("*") if p.is_file()}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report drift instead of writing")
    args = ap.parse_args()

    expected = expected_outputs()
    stale = sorted(existing_files() - expected.keys())
    changed = sorted(p for p, data in expected.items() if not p.exists() or p.read_bytes() != data)

    if args.check:
        for p in changed:
            print(f"out of date: {p.relative_to(ROOT)}")
        for p in stale:
            print(f"stale:       {p.relative_to(ROOT)}")
        if changed or stale:
            print("run: uv run python tools/sync_agent_profile.py")
            return 1
        print("agent profile in sync")
        return 0

    for p in changed:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(expected[p])
        print(f"wrote   {p.relative_to(ROOT)}")
    for p in stale:
        p.unlink()
        print(f"removed {p.relative_to(ROOT)}")
    print(f"{len(changed)} written, {len(stale)} removed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
